// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmpkrddcxjtxcqbkotoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtcGtyZGRjeGp0eGNxYmtvdG9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczOTg1MzMsImV4cCI6MjA2Mjk3NDUzM30.U76aJ90N3vtjix5UdPGpMy2fJi1JxMk35qw5J-a9wl8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);